export const dataList = [
  {
    id: 1,
    displayName: 'lounge resort',
    english: 'yes',
    language: 'spanish',
    gender: 'male',
    year: '2nd',
    age: 45,
    photoURL: '/images/places/ameri.jpg',
  },
  {
    id: 2,
    displayName: 'door urban',
    language: 'chinese',
    gender: 'male',
    year: '5th',
    age: 23,
    photoURL: '/images/places/italian.webp',
  },
  {
    id: 3,
    displayName: 'chow',
    language: 'hindi',
    gender: 'male',
    year: '4th',
    age: 54,
    photoURL: '/images/places/china.jpg',
  },
  {
    id: 4,
    displayName: 'wharf seafood',
    language: 'malayalam',
    gender: 'male',
    year: '2nd',
    age: 25,
    photoURL: '/images/places/sea.jpg',
  },
  {
    id: 5,
    displayName: 'Tossin',
    language: 'chinese',
    gender: 'other',
    year: '5th',
    age: 46,
    photoURL: '/images/places/italiian.jpg',
  },
  {
    id: 6,
    displayName: 'stories noodles',
    language: 'spanish',
    gender: 'other',
    year: '2nd',
    age: 76,
    photoURL: '/images/places/fookyew2.jpg',
  },
  {
    id: 7,
    displayName: 'Nacho cheeseburger',
    language: 'hindi',
    gender: 'other',
    year: '3rd',
    age: 34,
    photoURL: '/images/dishes/nacho-burger.jpg',
  },
  {
    id: 8,
    displayName: 'Mushroom Risotto',
    language: 'malayalam',
    gender: 'other',
    year: '4th',
    age: 65,
    photoURL: '/images/dishes/Mushroom-Risotto-Recipe-1-1200.jpg',
  },
  {
    id: 9,
    displayName: 'Shitake Fried Rice',
    language: 'spanish',
    gender: 'female',
    year: '1st',
    age: 33,
    photoURL: '/images/dishes/shiitake-salmon-fried-rice-0218-103230720.jpg',
  },
  {
    id: 10,
    displayName: 'Pesto chicken stew',
    language: 'chinese',
    gender: 'female',
    year: '1st',
    age: 22,
    photoURL: '/images/dishes/pesto-chicken.jpg',
  },
  {
    id: 11,
    displayName: 'Bruschetta',
    language: 'hindi',
    gender: 'female',
    year: '1st',
    age: 18,
    photoURL: '/images/dishes/as-tomato-bruschetta-articleLarge.jpg',
  },
    {
      id: 12,
      displayName: 'chinese',
      language: 'serbian',
      gender: 'female',
      year: '3rd',
      age: 19,
      photoURL: '/images/dishes/dimsums.jpg',
    },
  ];
